<template>
  <el-dialog
    v-model="visible"
    title="行程分享与导出"
    width="800px"
    @closed="handleClosed"
    class="trip-exporter-dialog"
  >
    <div class="exporter-tabs">
      <el-radio-group v-model="activeTab" size="large" class="export-tabs-group">
        <el-radio-button label="poster">分享海报</el-radio-button>
        <el-radio-button label="pdf">PDF行程单</el-radio-button>
        <el-radio-button label="link">复制链接</el-radio-button>
      </el-radio-group>
    </div>

    <div class="export-preview-container" v-loading="loading">
      <!-- Poster Preview -->
      <div v-if="activeTab === 'poster'" class="poster-preview">
        <div class="poster-canvas" ref="posterRef">
          <div class="poster-header">
            <div class="poster-title">{{ tripData.destination }} · 智能行程单</div>
            <div class="poster-subtitle">由 智慧旅游指南 为您精心制作</div>
          </div>
          
          <div class="poster-content">
            <div 
              v-for="(day, index) in tripData.itinerary" 
              :key="index" 
              class="poster-day"
            >
              <div class="day-num">DAY {{ index + 1 }}</div>
              <div class="day-activities">
                <div 
                  v-for="(act, actIndex) in day.activities" 
                  :key="actIndex" 
                  class="poster-activity"
                >
                  <span class="act-time">{{ act.time }}</span>
                  <span class="act-title">{{ act.title }}</span>
                </div>
              </div>
            </div>
          </div>
          
          <div class="poster-footer">
            <div class="qr-placeholder">
              <span class="qr-icon">🌍</span>
              <p>扫码查看完整行程</p>
            </div>
            <div class="footer-info">
              <p class="brand">TRAVEL SMART</p>
              <p class="tagline">记录每一段美好的旅程</p>
            </div>
          </div>
        </div>
        <div class="export-actions">
          <el-button type="primary" @click="exportPoster" :loading="exporting">保存海报图片</el-button>
        </div>
      </div>

      <!-- PDF Preview (Simplified list) -->
      <div v-else-if="activeTab === 'pdf'" class="pdf-preview">
        <div class="pdf-content-wrapper" ref="pdfRef">
          <div class="pdf-header">
            <h1>{{ tripData.destination }} 旅行计划</h1>
            <p>行程时段: {{ formattedDate }}</p>
            <p>出行人数: {{ tripData.people }}人 | 预算: ¥{{ tripData.budget }}</p>
          </div>
          <el-divider />
          <div class="pdf-days">
            <div v-for="(day, index) in tripData.itinerary" :key="index" class="pdf-day-item">
              <h2 class="pdf-day-title">Day {{ index + 1 }}: {{ day.title }}</h2>
              <div v-for="(act, actIdx) in day.activities" :key="actIdx" class="pdf-act-item">
                <div class="pdf-act-time">{{ act.time }}</div>
                <div class="pdf-act-detail">
                  <h3>{{ act.title }}</h3>
                  <p>{{ act.description }}</p>
                  <div class="pdf-act-tags">
                    <span v-for="tag in act.tags" :key="tag" class="pdf-tag">{{ tag }}</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="pdf-footer">
            Generated by Smart Travel Guide
          </div>
        </div>
        <div class="export-actions">
          <el-button type="primary" @click="exportPDF" :loading="exporting">下载 PDF 行程单</el-button>
        </div>
      </div>

      <!-- Link Copy -->
      <div v-else-if="activeTab === 'link'" class="link-copy-container">
        <el-result
          icon="success"
          title="生成成功"
          sub-title="您可以复制以下链接分享您的行程给好友"
        >
          <template #extra>
            <el-input v-model="shareUrl" readonly class="share-url-input">
              <template #append>
                <el-button @click="copyLink">复制</el-button>
              </template>
            </el-input>
          </template>
        </el-result>
      </div>
    </div>
  </el-dialog>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { ElMessage } from 'element-plus'

const props = defineProps<{
  modelValue: boolean
  tripData: {
    destination: string
    departure: string
    dateRange: any[]
    people: number
    budget: number
    itinerary: any[]
  }
}>()

const emit = defineEmits(['update:modelValue'])

const visible = computed({
  get: () => props.modelValue,
  set: (val) => emit('update:modelValue', val)
})

const activeTab = ref('poster')
const loading = ref(false)
const exporting = ref(false)
const posterRef = ref<HTMLElement | null>(null)
const pdfRef = ref<HTMLElement | null>(null)

const formattedDate = computed(() => {
  if (!props.tripData.dateRange || props.tripData.dateRange.length < 2) return '未指定'
  const start = new Date(props.tripData.dateRange[0]).toLocaleDateString()
  const end = new Date(props.tripData.dateRange[1]).toLocaleDateString()
  return `${start} - ${end}`
})

const shareUrl = computed(() => {
  const randomStr = Math.random().toString(36).slice(2, 11)
  return window.location.origin + '/share/' + randomStr
})

const exportPoster = async () => {
  if (!posterRef.value) return
  exporting.value = true
  try {
    const html2canvas = (await import('html2canvas')).default
    const canvas = await html2canvas(posterRef.value, {
      useCORS: true,
      scale: 2,
    })
    const link = document.createElement('a')
    link.download = `${props.tripData.destination}旅游海报.png`
    link.href = canvas.toDataURL('image/png')
    link.click()
    ElMessage.success('海报已保存')
  } catch (error) {
    console.error('Export error:', error)
    ElMessage.error('导出海报失败')
  } finally {
    exporting.value = false
  }
}

const exportPDF = async () => {
  if (!pdfRef.value) return
  exporting.value = true
  try {
    const html2canvas = (await import('html2canvas')).default
    const { jsPDF } = await import('jspdf')
    const canvas = await html2canvas(pdfRef.value, {
      scale: 2,
      useCORS: true
    })
    const imgData = canvas.toDataURL('image/png')
    const pdf = new jsPDF('p', 'mm', 'a4')
    const imgProps = pdf.getImageProperties(imgData)
    const pdfWidth = pdf.internal.pageSize.getWidth()
    const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width
    
    // Simple single page export, for complex multi-page we might need more logic
    pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight)
    pdf.save(`${props.tripData.destination}行程单.pdf`)
    ElMessage.success('PDF已导出')
  } catch (error) {
    console.error('PDF error:', error)
    ElMessage.error('导出PDF失败')
  } finally {
    exporting.value = false
  }
}

const copyLink = () => {
  navigator.clipboard.writeText(shareUrl.value).then(() => {
    ElMessage.success('链接已复制到剪贴板')
  })
}

const handleClosed = () => {
  activeTab.value = 'poster'
}
</script>

<style scoped lang="scss">
$primary-green: #4CAF50;
$dark-green: #2E7D32;
$light-green: #E8F5E8;

.trip-exporter-dialog {
  :deep(.el-dialog__body) {
    padding-top: 10px;
  }
}

.exporter-tabs {
  display: flex;
  justify-content: center;
  margin-bottom: 24px;
}

.poster-preview {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 20px;
}

.poster-canvas {
  width: 375px;
  background: white;
  border-radius: 16px;
  overflow: hidden;
  box-shadow: 0 10px 40px rgba(0,0,0,0.1);
  padding-bottom: 30px;
}

.poster-header {
  background: linear-gradient(135deg, $primary-green 0%, $dark-green 100%);
  padding: 40px 30px;
  color: white;
  text-align: center;
  
  .poster-title {
    font-size: 24px;
    font-weight: 700;
    margin-bottom: 8px;
  }
  
  .poster-subtitle {
    font-size: 14px;
    opacity: 0.9;
  }
}

.poster-content {
  padding: 24px;
  
  .poster-day {
    margin-bottom: 20px;
    
    .day-num {
      display: inline-block;
      background: $light-green;
      color: $dark-green;
      font-weight: 700;
      padding: 4px 12px;
      border-radius: 20px;
      font-size: 12px;
      margin-bottom: 12px;
    }
    
    .day-activities {
      border-left: 2px dashed $primary-green;
      padding-left: 16px;
      margin-left: 10px;
    }
    
    .poster-activity {
      display: flex;
      gap: 12px;
      margin-bottom: 10px;
      font-size: 14px;
      
      .act-time {
        color: $primary-green;
        font-weight: 600;
        min-width: 45px;
      }
      
      .act-title {
        color: #333;
      }
    }
  }
}

.poster-footer {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 20px 30px;
  border-top: 1px solid #eee;
  
  .qr-placeholder {
    text-align: center;
    .qr-icon {
      font-size: 32px;
    }
    p {
      font-size: 10px;
      color: #999;
      margin-top: 4px;
    }
  }
  
  .footer-info {
    text-align: right;
    .brand {
      font-weight: 800;
      color: $dark-green;
      font-size: 16px;
    }
    .tagline {
      font-size: 10px;
      color: #999;
    }
  }
}

.pdf-preview {
  background: #f5f7f9;
  padding: 20px;
  border-radius: 8px;
  max-height: 500px;
  overflow-y: auto;
}

.pdf-content-wrapper {
  background: white;
  padding: 40px;
  width: 100%;
  box-sizing: border-box;
  
  .pdf-header {
    text-align: center;
    h1 {
      color: $dark-green;
      margin-bottom: 15px;
    }
    p {
      color: #666;
      margin: 5px 0;
    }
  }
  
  .pdf-day-item {
    margin-bottom: 30px;
    
    .pdf-day-title {
      font-size: 20px;
      color: $dark-green;
      border-bottom: 1px solid $primary-green;
      padding-bottom: 8px;
      margin-bottom: 15px;
    }
    
    .pdf-act-item {
      display: flex;
      gap: 20px;
      margin-bottom: 20px;
      
      .pdf-act-time {
        font-weight: 700;
        color: $primary-green;
        min-width: 60px;
      }
      
      .pdf-act-detail {
        h3 {
          margin: 0 0 8px 0;
          font-size: 16px;
        }
        p {
          color: #666;
          font-size: 14px;
          margin: 0 0 10px 0;
          line-height: 1.6;
        }
        .pdf-act-tags {
          display: flex;
          gap: 8px;
          .pdf-tag {
            background: #f0fdf4;
            color: $primary-green;
            padding: 2px 8px;
            border-radius: 4px;
            font-size: 12px;
            border: 1px solid $primary-green;
          }
        }
      }
    }
  }
  
  .pdf-footer {
    text-align: center;
    color: #ccc;
    font-size: 12px;
    margin-top: 40px;
  }
}

.export-actions {
  display: flex;
  justify-content: center;
  margin-top: 24px;
}

.share-url-input {
  width: 400px;
}
</style>
